block_builder: promotee tags might have siblings
eg

```html
<div>
    <blockquote></blockquote>
    <tag></tag>
    <blockquote></blockquote>
</div>
```

Needs to become
```html
<blockquote></blockquote>
<div>
    <tag></tag>
</div>
<blockquote></blockquote>
```

Before it became
```html
<blockquote></blockquote>
```

This solves the following crash
ValueError: Cannot replace one element with another when the element to be replaced is not part of a tree.

Related #141